# Generated by Django 3.2.15 on 2022-08-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo_parametro', models.CharField(max_length=25, verbose_name='Tipo de Parametro')),
            ],
        ),
    ]
