# Generated by Django 3.2.15 on 2022-08-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_empleado')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('empresa', models.CharField(max_length=25, verbose_name='empresa')),
            ],
        ),
    ]
