version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: DesarrolloWeb/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./DesarrolloWeb/:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  back2:
    build: ./modulo-preprocesado-datos-JS/
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./modulo-preprocesado-datos-JS/:/code
    ports:
      - "8001:8001"
    environment:
    - POSTGRES_NAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

