# Generated by Django 3.2.15 on 2022-09-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosAFP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150, verbose_name='Descripción del descuento por concepto de AFP')),
                ('porcentaje_descuento_empleado', models.FloatField(verbose_name='Porcentaje de descuento empleado')),
                ('porcentaje_descuento_empresa', models.FloatField(verbose_name='Porcentaje de descuento para la empresa')),
                ('porcentaje_descuento_total', models.FloatField(verbose_name='Porcentaje de descuento total')),
                ('limite_inferior', models.FloatField(verbose_name='Minima cantidad de SMMLV para el concepto')),
                ('limite_superior', models.FloatField(verbose_name='Maxima cantidad de SMMLV para el concepto (excluyente)')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosARL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150, verbose_name='Descripción del descuento por concepto de ARL')),
                ('porcentaje_descuento_empleado', models.FloatField(verbose_name='Porcentaje de descuento empleado')),
                ('porcentaje_descuento_empresa', models.FloatField(verbose_name='Porcentaje de descuento para la empresa')),
                ('porcentaje_descuento_total', models.FloatField(verbose_name='Porcentaje de descuento total')),
                ('nivel_riesgo', models.IntegerField(verbose_name='Nivel de riesgo para aplicar concepto')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosCAJA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150, verbose_name='Descripción del descuento por concepto de caja')),
                ('porcentaje_descuento_empleado', models.FloatField(verbose_name='Porcentaje de descuento empleado')),
                ('porcentaje_descuento_empresa', models.FloatField(verbose_name='Porcentaje de descuento para la empresa')),
                ('porcentaje_descuento_total', models.FloatField(verbose_name='Porcentaje de descuento total')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosEPS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150, verbose_name='Descripción del descuento por concepto de EPS')),
                ('porcentaje_descuento_empleado', models.FloatField(verbose_name='Porcentaje de descuento empleado')),
                ('porcentaje_descuento_empresa', models.FloatField(verbose_name='Porcentaje de descuento para la empresa')),
                ('porcentaje_descuento_total', models.FloatField(verbose_name='Porcentaje de descuento total')),
                ('limite_inferior', models.FloatField(verbose_name='Minima cantidad de SMMLV para el concepto')),
                ('limite_superior', models.FloatField(verbose_name='Maxima cantidad de SMMLV para el concepto (excluyente)')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosFSP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150, verbose_name='Descripción del descuento por concepto de FSP')),
                ('porcentaje_descuento_empleado', models.FloatField(verbose_name='Porcentaje de descuento empleado')),
                ('porcentaje_descuento_empresa', models.FloatField(verbose_name='Porcentaje de descuento para la empresa')),
                ('porcentaje_descuento_total', models.FloatField(verbose_name='Porcentaje de descuento total')),
                ('limite_inferior', models.FloatField(verbose_name='Minima cantidad de SMMLV para el concepto')),
                ('limite_superior', models.FloatField(verbose_name='Maxima cantidad de SMMLV para el concepto (excluyente)')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosICBF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150, verbose_name='Descripción del descuento por concepto de aportes ICBF')),
                ('porcentaje_descuento_empleado', models.FloatField(verbose_name='Porcentaje de descuento empleado')),
                ('porcentaje_descuento_empresa', models.FloatField(verbose_name='Porcentaje de descuento para la empresa')),
                ('porcentaje_descuento_total', models.FloatField(verbose_name='Porcentaje de descuento total')),
                ('limite_inferior', models.FloatField(verbose_name='Minima cantidad de SMMLV para el concepto')),
                ('limite_superior', models.FloatField(verbose_name='Maxima cantidad de SMMLV para el concepto (excluyente)')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosSENA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150, verbose_name='Descripción del descuento por concepto de aportes SENA')),
                ('porcentaje_descuento_empleado', models.FloatField(verbose_name='Porcentaje de descuento empleado')),
                ('porcentaje_descuento_empresa', models.FloatField(verbose_name='Porcentaje de descuento para la empresa')),
                ('porcentaje_descuento_total', models.FloatField(verbose_name='Porcentaje de descuento total')),
                ('limite_inferior', models.FloatField(verbose_name='Minima cantidad de SMMLV para el concepto')),
                ('limite_superior', models.FloatField(verbose_name='Maxima cantidad de SMMLV para el concepto (excluyente)')),
            ],
        ),
        migrations.DeleteModel(
            name='Globales',
        ),
        migrations.DeleteModel(
            name='Topes',
        ),
    ]
