# Generated by Django 3.2.15 on 2022-09-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0002_alter_periodo_mes_periodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='cod_periodo',
            new_name='id_periodo',
        ),
    ]
