# Generated by Django 3.2.15 on 2022-09-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0003_rename_cod_periodo_periodo_id_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadesSG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_miplanilla', models.CharField(max_length=30)),
                ('nit', models.CharField(max_length=30)),
                ('dv', models.CharField(max_length=1)),
                ('razon_social', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=30)),
                ('tipo_entidad', models.CharField(choices=[('eps', 'EPS'), ('afp', 'AFP'), ('ccf', 'CCF')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosGlobales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('unidad_medida', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ARL',
        ),
        migrations.DeleteModel(
            name='EPS',
        ),
        migrations.DeleteModel(
            name='FondoPension',
        ),
        migrations.AddField(
            model_name='empresa',
            name='aplica_exoneracion',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='module',
            field=models.CharField(choices=[('preprocesado', 'Preprocesado'), ('conceptos', 'Conceptos'), ('parametros', 'Parametros'), ('liquidaciones', 'Liquidaciones'), ('empresas', 'Empresas')], max_length=30),
        ),
    ]
