# Generated by Django 3.2.15 on 2022-09-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0004_auto_20220903_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptointerno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
