# Generated by Django 3.2.15 on 2022-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0004_auto_20220924_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadesSG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_miplanilla', models.CharField(max_length=30)),
                ('nit', models.CharField(max_length=30)),
                ('dv', models.CharField(max_length=1)),
                ('razon_social', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=30)),
                ('tipo_entidad', models.CharField(choices=[('eps', 'EPS'), ('afp', 'AFP'), ('ccf', 'CCF')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ARL',
        ),
        migrations.DeleteModel(
            name='EPS',
        ),
        migrations.DeleteModel(
            name='FondoPension',
        ),
    ]
