# Generated by Django 3.2.15 on 2022-09-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0005_alter_conceptointerno_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptoempresa',
            old_name='id_empresa',
            new_name='empresa',
        ),
    ]
