# Generated by Django 3.2.15 on 2022-09-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0005_auto_20220925_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptoempresa',
            name='concepto_interno',
        ),
        migrations.AddField(
            model_name='conceptoempresa',
            name='cod_concepto',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptoempresa',
            name='cuenta_contable',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptoempresa',
            name='desc_cuenta',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptoempresa',
            name='observacion',
            field=models.CharField(default=1, max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptoempresa',
            name='tipo_clasificacion',
            field=models.CharField(choices=[('salarial', 'Salarial'), ('no_salarial', 'NoSalarial'), ('na', 'NoAplica')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptoempresa',
            name='tipo_concepto',
            field=models.CharField(choices=[('devengo', 'Devengo'), ('descuento', 'Descuento')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptoempresa',
            name='tipo_novedad',
            field=models.CharField(choices=[('vac', 'Vacaciones'), ('ige', 'IncapacidadEPS'), ('irl', 'IncapacidadARL'), ('lma', 'LicenciaMaternidad'), ('sln', 'Suspension'), ('avp', 'AporteVoluntario')], default='na', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='siglas',
            field=models.CharField(default=11, max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptoempresa',
            name='id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='cod_concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.conceptoempresa'),
        ),
        migrations.DeleteModel(
            name='ConceptoInterno',
        ),
    ]
