# Generated by Django 3.2.15 on 2022-09-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0006_rename_id_empresa_conceptoempresa_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptoempresa',
            old_name='id_concepto_interno',
            new_name='concepto_interno',
        ),
    ]
