# Generated by Django 3.2.15 on 2022-09-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0007_rename_id_concepto_interno_conceptoempresa_concepto_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptointerno',
            name='tipo_concepto',
            field=models.CharField(choices=[('Salarial', 'Salarial'), ('No salarial', 'No salarial')], default='Salarial', max_length=12),
        ),
    ]
