# Generated by Django 3.2.15 on 2022-09-14 05:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liquidaciones', '0009_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('csv', models.FileField(upload_to='path/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
