# Generated by Django 3.2.15 on 2022-09-20 02:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liquidaciones', '0010_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preprocesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_1', models.FileField(upload_to='path/', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('file_2', models.FileField(upload_to='path/', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('periodo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('estado', models.CharField(choices=[('cargado', 'Cargado'), ('aprobado', 'Aprobado')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
