# Generated by Django 3.2.15 on 2022-09-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0011_auto_20220920_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='id_periodo',
            new_name='cod_periodo',
        ),
    ]
