# Generated by Django 3.2.15 on 2022-09-21 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0012_rename_id_periodo_periodo_cod_periodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomina',
            old_name='id_empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='nomina',
            old_name='id_periodo',
            new_name='periodo',
        ),
    ]
