# Generated by Django 3.2.15 on 2022-08-28 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_miplanilla', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoInterno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_concepto', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=75, verbose_name='Nombre de la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_miplanilla', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FondoPension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_miplanilla', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Globales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_global', models.CharField(max_length=75)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tope', models.CharField(max_length=75)),
                ('clasificacion', models.CharField(max_length=100)),
                ('limite_superior', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('no_personal', models.IntegerField()),
                ('primer_apellido', models.CharField(default='', max_length=75)),
                ('segundo_apellido', models.CharField(default='', max_length=75)),
                ('primer_nombre', models.CharField(default='', max_length=75)),
                ('segundo_nombre', models.CharField(default='', max_length=75)),
                ('tipo_documento', models.CharField(default='', max_length=75)),
                ('documento', models.CharField(default='', max_length=75, primary_key=True, serialize=False)),
                ('division_persona', models.CharField(default='', max_length=75)),
                ('denominacion_funcion', models.CharField(default='', max_length=75)),
                ('und_tiempo_nomina', models.CharField(default='', max_length=75)),
                ('cc', models.CharField(default='', max_length=75)),
                ('cuenta_bancaria', models.CharField(default='', max_length=75)),
                ('clase_contrato', models.CharField(default='', max_length=75)),
                ('procedimiento_retencion', models.CharField(default='', max_length=75)),
                ('porcentaje_retencion', models.FloatField()),
                ('declarante_renta', models.CharField(default='', max_length=75)),
                ('tiene_independientes', models.CharField(default='', max_length=75)),
                ('importe', models.FloatField()),
                ('moneda', models.CharField(default='', max_length=75)),
                ('texto_breve', models.CharField(default='', max_length=75)),
                ('correo_electronico', models.CharField(default='', max_length=75)),
                ('centro_coste', models.CharField(default='', max_length=75)),
                ('fecha', models.DateField()),
                ('grupo_personal', models.CharField(default='', max_length=75)),
                ('clase', models.CharField(default='', max_length=75)),
                ('desde', models.DateField(default='')),
                ('denominacion_posicion', models.CharField(default='', max_length=75)),
                ('denominacion_medicion', models.CharField(default='', max_length=75)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.empresa')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_personal', models.IntegerField()),
                ('apellido_nombre', models.CharField(max_length=75)),
                ('nombre_completo', models.CharField(max_length=75)),
                ('NIF', models.CharField(max_length=75)),
                ('divp', models.CharField(max_length=75)),
                ('division_persona', models.CharField(max_length=75)),
                ('percalnom', models.CharField(max_length=75)),
                ('area_nomina', models.CharField(max_length=75)),
                ('paper', models.CharField(max_length=75)),
                ('denom_periodos', models.CharField(max_length=75)),
                ('periodo_inicia', models.IntegerField()),
                ('fecha_inicia', models.DateField()),
                ('tpclcnom', models.CharField(max_length=75)),
                ('idnom', models.CharField(max_length=75)),
                ('area_cal_nom', models.CharField(max_length=75)),
                ('area_nomina2', models.CharField(max_length=75)),
                ('paper2', models.CharField(max_length=75)),
                ('denom_periodos2', models.CharField(max_length=75)),
                ('periodo_fin', models.IntegerField()),
                ('fecha_fin', models.DateField()),
                ('tpclcnom2', models.CharField(max_length=75)),
                ('idnom2', models.CharField(max_length=75)),
                ('ag_pai', models.CharField(max_length=75)),
                ('desc_concepto', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('importe', models.FloatField()),
                ('moneda', models.CharField(max_length=75)),
                ('cod_concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.conceptointerno')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.empresa')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoEmmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_concepto', models.CharField(max_length=150)),
                ('id_concepto_interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.conceptointerno')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.empresa')),
            ],
        ),
    ]
