# Generated by Django 3.2.15 on 2022-08-27 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=75, verbose_name='Nombre de la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.empresa')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.periodo')),
            ],
        ),
    ]
